FROM node:22-alpine AS base
ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"
RUN corepack enable
WORKDIR /app
COPY package.json pnpm-lock.yaml ./

FROM base AS prod-deps
RUN --mount=type=cache,id=pnpm,target=/pnpm/store pnpm install --prod --frozen-lockfile

FROM base AS builder
RUN --mount=type=cache,id=pnpm,target=/pnpm/store pnpm install --frozen-lockfile
COPY . .
RUN pnpm build

FROM base AS production
WORKDIR /app
COPY .env.production .
COPY --from=prod-deps /app/node_modules node_modules/
# Build files generated by Sveltekit
COPY --from=builder /app/build build/
# DB migrations generated by Drizzle
COPY --from=builder /app/drizzle drizzle/
# Drizzle configuration needed for running migrations
COPY --from=builder /app/drizzle-prod.config.ts .
RUN apk add --no-cache ffmpeg=~6.1.2 exiftool=~13.30
VOLUME /app/data
VOLUME /app/library
EXPOSE 3990
CMD ["pnpm", "start"]